language: python
matrix:
  include:
  - os: linux
    python: "2.7"
    dist: trusty
  - os: osx
    language: generic
    python: 2.7
# command to install dependencies
install:
- pip install -e '.[test]'
# command to run tests
script:
- make test
# upload code coverage result to Coveralls if tests passing
after_success:
- coveralls